package schema

import "time"

/*
   This code is generated by gendry
   ginger-cli schema -d ginger_db -t user_oauth2
*/

const UserTableName = "user"

// User is a mapping object for user table in mysql
type User struct {
	ID       uint      `ddb:"id"`
	Name     string    `ddb:"name"`
	Age      byte      `ddb:"age"`
	Avatar   string    `ddb:"avatar"`
	Gender   int8      `ddb:"gender"`
	Email    string    `ddb:"email"`
	Phone    string    `ddb:"phone"`
	Password string    `ddb:"password"`
	Salt     string    `ddb:"salt"`
	Status   int8      `ddb:"status"`
	UpdateAt time.Time `ddb:"update_at"`
	CreateAt time.Time `ddb:"create_at"`
}

func (*User)TableName() string  {
	return UserTableName
}